import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function MyHome() {
  return (
    <>
      <Head>
        <title>MathEase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div>
          <p className="underlin text-xl ml-2 pt-10">Welcome</p>
        </div>
      </section>
    </>
  )
}
