import Head from 'next/head'
import { Imprima, Inter } from '@next/font/google'
import Image from 'next/image'
import { gsap } from "gsap";
import NavBar from '@/components/Navabr/NavBar';
import MobileNavBar from '@/components/Navabr/mobileNavBar';
import MathInput from '@/components/InputBox/mathQuestion';
import NaturalLanguagInput from '@/components/InputBox/naturalLanguageInput';
import Link from 'next/link';
import logo from '../public/images/logo.png';


export default function MyHome() {

  // to prevent 'document' not defined error
  if (typeof document !== 'undefined') {
    let rocket = document.querySelector('#rocket')
    let heroText = document.querySelector('#heroText > p')
    let heroText2 = document.querySelector('#heroText2 > p')
    // let card1 = document.querySelector('#card1')
    
    // Rocket animation
    function aniateRocket() {
      const tl = gsap.timeline({defaults: {duration: 2}});
    
      tl.fromTo(rocket, {x: -20, y: -15}, {x: 5, y: 5 , yoyo: true, repeat: -1, yoyoEase: true})
    }

    // Hero text animation
    function animateText() {
      const tl = gsap.timeline({defaults: {duration: 1}});

      tl.fromTo(heroText, {y: 100, skewY: 10, opacity: 0}, {y: 0, ease: "Power4.out", skewY: 0, opacity: 1, stagger: {amount: 0.8}})
      tl.fromTo(heroText2, {y: 100, skewY: 10, opacity: 0}, {y: 0, ease: "Power4.out", skewY: 0, opacity: 1})
    }

    animateText()
    aniateRocket()
  }

  return (
    <>
      <Head>
        <title>MathEase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <section className='w-full h-[700px] sm:h-[627px] bg-[url(../public/images/bg-img.png)] bg-cover bg-center overflow-hidden'>
        {/* ****************** NAVIGATIN BAR ******************** */}
        <NavBar />
        <MobileNavBar />
        {/* ****************** HERO CONTENTS ******************** */}
        <div className='sm:flex justify-between max-w-[90%] sm:max-w-[80%] m-auto'>
          <div className=' mt-10 sm:mt-28 text-white max-w-sm sm:max-w-2xl'>
            <div id="heroText" className=' relative overflow-hidden'>
              <p className=' text-[23px] text-center sm:text-left sm:text-[40px] pb-2'>Welcome to MathEase, Your Intelligent Math Problem Solver.</p>
              <div id="heroText2">
                <p className='max-w-[500px] text-[14px] sm:text-[16px] text-center sm:text-left'>
                  Harnessing the latest advancements in computational intelligence, 
                  MathEase empowers you to tackle intricate equations, calculus problems, 
                  algebraic expressions, and more, effortlessly.
                  <br />
                  Unlock the Power of Computational Intelligence!
                </p>
              </div>
            </div>
          </div>
          <Image className='sm:mr-[-180px]' id="rocket" src="/images/3d-rocket.png" alt="Rocket" width="600" height="600"/>
        </div>
      </section>
      <section>
        <MathInput />
      </section>
      {/* HOW IT WORKS SECTION */}
      <section className='bg-gray-100 mt-20 py-4 pb-20'>
        <p className=' text-center text-[40px] m-10'>How it works in 3 easy steps</p>
        <div className='flex flex-col sm:flex-row gap-y-4 sm:gap-y-0 max-w-[800px] mx-auto justify-between gap-3'>
          <div id="card1" className='flex mx-auto md:mx-0 w-[300px] items-center text-center bg-white rounded-lg shadow-xl pr-6 py-8 hover:shadow-2xl'>
            <Image src="/images/hands-one.png" width="100" height="100" alt="hand-one"/>
            <p className=' text-[11px]'>Enter your search prompt in the input field above. Example prompt &quot;solve 3x - 15 = 10&quot;</p>
          </div>
          <div id="card3" className='flex mx-auto md:mx-0 w-[300px] items-center text-center bg-white rounded-lg shadow-xl pr-6 py-8 hover:shadow-2xl'>
            <Image src="/images/hands-two.png" width="100" height="100" alt="hand-two"/>
            <p className=' text-[11px]'>Click the submit button and wait for the system to generate your answer.</p>
          </div>
          <div id="card2" className='flex mx-auto md:mx-0 w-[300px] items-center text-center bg-white rounded-lg shadow-xl pr-6 py-8 hover:shadow-2xl'>
            <Image src="/images/hands-three.png" width="100" height="100" alt="hand-three"/>
            <p className=' text-[11px] ml-6'>And... you&apos;re all set</p>
          </div>
        </div>
      </section>
      {/* Natural language section */}
      <section>
        <NaturalLanguagInput />
      </section>
      <footer className='bg-[url(../public/images/footer-bg.png)] w-full sm:h-[768px] bg-cover bg-center overflow-hidden'>
        <div className='text-white mt-[300px] w-[80%] m-auto flex flex-col md:flex-row gap-10 justify-between'>
          <Link href="/" className='flex gap-5 items-center'>
            <Image src={logo} width={80}/>
            <h1 className="text-[30px] sm:text-[40px]">MATHEASE</h1>
          </Link>
          <div>
            <p className='text-[25px] py-5'>Navigate.</p>
            <ul>
              <li><Link href="/products">Our Products.</Link></li>
              <li><Link href="/about">About.</Link></li>
            </ul>
          </div>
          <div>
            <p className='text-[25px] py-5'>Legal.</p>
            <ul>
              <li><Link href="/products">Terms & Conditions</Link></li>
            </ul>
          </div>
          <div>
            <p className='text-[25px] py-5'>Contact Us.</p>
            <ul>
              <li><Link href="/products">Phone +234-90-000-0000</Link></li>
              <li><Link href="/about">Email: mathease.org@email.com</Link></li>
            </ul>
          </div>
        </div>
        <div className='sm:relative sm:top-56 my-5 sm:my-0 text-white bg-purple-800 rounded-2xl max-w-max m-auto p-5'>
          Made with ❤ by Hameed Osilaja.
        </div>
      </footer>
    </>
  )
}
